var sanPham = [
  {
    name: "Valini Coffee",
    price: 50,
    img: "./img/ImgThucUong/VaniliCoffee.jpg",
    id: "clickMua1",
    reMove: "clickXoa1",
    count: 1,
  },
  {
    name: "Trà Cocktail",
    price: 55,
    img: "./img/ImgThucUong/TraCocktail.jpg",
    id: "clickMua2",
    reMove: "clickXoa2",
    count: 1,
  },
  {
    name: "Dâu Ép",
    price: 45,
    img: "./img/ImgThucUong/DauEp.jpg",
    id: "clickMua3",
    reMove: "clickXoa3",
    count: 1,
  },
  {
    name: "Chocolate Coffee",
    price: 40,
    img: "./img/ImgThucUong/ChocolateCoffee.jpg",
    id: "clickMua4",
    reMove: "clickXoa4",
    count: 1,
  },
  {
    name: "Cappucchino",
    price: 37,
    img: "./img/ImgThucUong/Cappucchino.png",
    id: "clickMua5",
    reMove: "clickXoa5",
    count: 1,
  },
  {
    name: "Trà Xanh Đá Xay",
    price: 35,
    img: "./img/ImgThucUong/TraXanhDaXay.png",
    id: "clickMua6",
    reMove: "clickXoa6",
    count: 1,
  },
  {
    name: "Socola Kem Đá Xay",
    price: 45,
    img: "./img/ImgThucUong/SocolaKemDaXay.png",
    id: "clickMua7",
    reMove: "clickXoa7",
    count: 1,
  },
  {
    name: "Trà Đào",
    price: 40,
    img: "./img/ImgThucUong/TraDao.png",
    id: "clickMua8",
    reMove: "clickXoa8",
    count: 1,
  },
  {
    name: "Chocolate Đá Say",
    price: 50,
    img: "./img/ImgThucUong/ChocolataDaSay.png",
    id: "clickMua9",
    reMove: "clickXoa9",
    count: 1,
  },
  {
    name: "Trà Sữa",
    price: 48,
    img: "./img/ImgThucUong/TraSua.jpg",
    id: "clickMua10",
    reMove: "clickXoa10",
    count: 1,
  },
  {
    name: "Trà Vải Sen",
    price: 45,
    img: "./img/ImgThucUong/TraVaiSen.jpg",
    id: "clickMua11",
    reMove: "clickXoa11",
    count: 1,
  },
  {
    name: "Ice Blend Coffee",
    price: 45,
    img: "./img/ImgThucUong/ICEBLENDED.png",
    id: "clickMua12",
    reMove: "clickXoa12",
    count: 1,
  },
  {
    name: "Cà Phê Caramel Đá Xay",
    price: 53,
    img: "./img/ImgThucUong/CoffeeCaramelDaXay.png",
    id: "clickMua13",
    reMove: "clickXoa13",
    count: 1,
  },
  {
    name: "Caramel Đá Xay",
    price: 49,
    img: "./img/ImgThucUong/CaramelDaXay.png",
    id: "clickMua14",
    reMove: "clickXoa14",
    count: 1,
  },
  {
    name: "Táo Và Dâu Ép",
    price: 56,
    img: "./img/ImgThucUong/TaoVaDauEp.jpg",
    id: "clickMua15",
    reMove: "clickXoa15",
    count: 1,
  },
  {
    name: "Bưởi Ép",
    price: 55,
    img: "./img/ImgThucUong/BuoiEp.png",
    id: "clickMua16",
    reMove: "clickXoa16",
    count: 1,
  },
  {
    name: "Cam Ép",
    price: 40,
    img: "./img/ImgThucUong/CamEp.png",
    id: "clickMua17",
    reMove: "clickXoa17",
    count: 1,
  },
  {
    name: "Ổi Ép",
    price: 45,
    img: "./img/ImgThucUong/OiEp.png",
    id: "clickMua18",
    reMove: "clickXoa18",
    count: 1,
  },
  {
    name: "Sinh Tố Xoài",
    price: 46,
    img: "./img/ImgThucUong/SinhToXoai.png",
    id: "clickMua19",
    reMove: "clickXoa19",
    count: 1,
  },
  {
    name: "Sinh Tố Chanh",
    price: 42,
    img: "./img/ImgThucUong/SinhToChanh.png",
    id: "clickMua20",
    reMove: "clickXoa20",
    count: 1,
  },
  {
    name: "Sinh Tố Chuối",
    price: 48,
    img: "./img/ImgThucUong/SinhToChuoi.png",
    id: "clickMua21",
    reMove: "clickXoa21",
    count: 1,
  },
  {
    name: "Bánh Oreo Xay Cùng Cà Phê",
    price: 51,
    img: "./img/ImgThucUong/BanhOreo.png",
    id: "clickMua22",
    reMove: "clickXoa22",
    count: 1,
  },
  {
    name: "Cà Phê Sữa",
    price: 35,
    img: "./img/ImgThucUong/CoffeeSua.png",
    id: "clickMua23",
    reMove: "clickXoa23",
    count: 1,
  },
  {
    name: "Cà Phê Cappuccino",
    price: 35,
    img: "./img/ImgThucUong/Cappuccino.png",
    id: "clickMua24",
    reMove: "clickXoa24",
    count: 1,
  },
  {
    name: "Sô-Cô-La",
    price: 40,
    img: "./img/ImgThucUong/Socola.png",
    id: "clickMua25",
    reMove: "clickXoa25",
    count: 1,
  },
  {
    name: "Cà Phê Latte",
    price: 45,
    img: "./img/ImgThucUong/Latte.png",
    id: "clickMua26",
    reMove: "clickXoa26",
    count: 1,
  },
  {
    name: "Cà Phê Caramel",
    price: 45,
    img: "./img/ImgThucUong/Caramel.png",
    id: "clickMua27",
    reMove: "clickXoa27",
    count: 1,
  },
  {
    name: "Cà Phê Vanilla",
    price: 42,
    img: "./img/ImgThucUong/Caramel.png",
    id: "clickMua28",
    reMove: "clickXoa28",
    count: 1,
  },
  {
    name: "Trà Lài",
    price: 30,
    img: "./img/ImgThucUong/TraXanh.png",
    id: "clickMua29",
    reMove: "clickXoa29",
    count: 1,
  },
  {
    name: "Trà Xanh",
    price: 32,
    img: "./img/ImgThucUong/TraXanh.png",
    id: "clickMua30",
    reMove: "clickXoa30",
    count: 1,
  },
  {
    name: "Trà Ô Long",
    price: 35,
    img: "./img/ImgThucUong/TraXanh.png",
    id: "clickMua31",
    reMove: "clickXoa31",
    count: 1,
  },
  {
    name: "Trà Sen",
    price: 37,
    img: "./img/ImgThucUong/TraXanh.png",
    id: "clickMua32",
    reMove: "clickXoa32",
    count: 1,
  },
  {
    name: "Trà Đen, Kem Sữa",
    price: 55,
    img: "./img/ImgThucUong/TraDen.png",
    id: "clickMua33",
    reMove: "clickXoa33",
    count: 1,
  },
  {
    name: "Thơm Và Dâu Ép",
    price: 50,
    img: "./img/ImgThucUong/ThomDauEp.png",
    id: "clickMua34",
    reMove: "clickXoa34",
    count: 1,
  },
  {
    name: "Táo Ép",
    price: 45,
    img: "./img/ImgThucUong/TaoEp.png",
    id: "clickMua35",
    reMove: "clickXoa35",
    count: 1,
  },
  {
    name: "Dứa Ép",
    price: 46,
    img: "./img/ImgThucUong/DuaEp.png",
    id: "clickMua36",
    reMove: "clickXoa36",
    count: 1,
  },
  {
    name: "Vitamin C (Xoài, Cam)",
    price: 55,
    img: "./img/ImgThucUong/VitaminC.png",
    id: "clickMua37",
    reMove: "clickXoa37",
    count: 1,
  },
  {
    name: "Sinh Tố Trái Cây Nhiệt Đới",
    price: 56,
    img: "./img/ImgThucUong/NhietDoi.png",
    id: "clickMua38",
    reMove: "clickXoa38",
    count: 1,
  },
];
